name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run hosty with sudo
        run: sudo $GITHUB_WORKSPACE/hosty.sh
      - name: Run hosty in debug mode
        run: $GITHUB_WORKSPACE/hosty.sh -d
      #- name: Run hosty installer without sudo
      #  run: $GITHUB_WORKSPACE/install.sh
      #- name: Run hosty installer with sudo
      #  run: sudo $GITHUB_WORKSPACE/install.sh
      - name: Run hosty updater in debug mode
        run: $GITHUB_WORKSPACE/updater.sh -d
  test-mac:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run hosty with sudo
        run: sudo $GITHUB_WORKSPACE/hosty.sh
      - name: Run hosty in debug mode
        run: $GITHUB_WORKSPACE/hosty.sh -d
      #- name: Run hosty installer without sudo
      #  run: $GITHUB_WORKSPACE/install.sh
      #- name: Run hosty installer with sudo
      #  run: sudo $GITHUB_WORKSPACE/install.sh
      - name: Run hosty updater in debug mode
        run: $GITHUB_WORKSPACE/updater.sh -d
